region            = "eu-west-2"
aws_access_key    = "YOUR_ACCESS_KEY"
aws_secret_key    = "YOUR_SECRET_KEY"
ami               = "ami-0aef57767f5404a35"
name              = "wordpress_db"
username          = "db_user"
password          = "db_password"
